version: '3.9'

services:
  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80

  backend:
    build: ./backend
    user: root
    ports:
      - '9000:9000'
    volumes:
      - symfony:/usr/src/app

  nginx:
    image: nginx:stable
    user: root
    ports:
      - 8080:80
    volumes:
      - symfony:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - database

  frontend:
    build: ./frontend
    ports:
      - 8081:8080
    entrypoint: npm run start


volumes:
  symfony:
