version: '3.9'

services:
  database:
    image: mysql:8
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - 8083:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80

  backend:
    build: 
      context: ../backend
      dockerfile: ../backend/docker/dev.Dockerfile
    environment:
      - DATABASE_URL
    ports:
      - 9000:9000
    volumes:
      - ../backend:/var/www/backend
    depends_on:
      - database

  nginx:
    image: nginx:stable
    ports:
      - 8081:80
    volumes:
      - ../backend:/var/www/backend
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    build: 
      context: ../frontend
      dockerfile: ../frontend/docker/dev.Dockerfile
    environment:
      - WATCHPACK_POLLING="true"
      - JOB_SERVICE_URL
      - PROPERTY_SERVICE_URL
    volumes:
      - ../frontend:/var/www/frontend
    entrypoint: "npm run start"
    ports:
      - 8080:8080


